# This file was auto-generated by Fern from our API Definition.

from seed.client import AsyncSeedExhaustive, SeedExhaustive

from ...utilities import validate_response


async def test_get_exception(client: SeedExhaustive, async_client: AsyncSeedExhaustive) -> None:
    expected_response = {
        "type": "generic",
        "exceptionType": "Unavailable",
        "exceptionMessage": "This component is unavailable!",
        "exceptionStacktrace": "<logs>",
    }
    expected_types = {"exceptionType": None, "exceptionMessage": None, "exceptionStacktrace": None}
    response = client.file.notification.service.get_exception(notification_id="notification-hsy129x")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.file.notification.service.get_exception(notification_id="notification-hsy129x")
    validate_response(async_response, expected_response, expected_types)
